version: '3.4'
services:

  chrome:
    image: selenium/node-chrome:4.3.0-20220624
    shm_size: 2gb
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2 #number of browsers
    networks: 
      - network1
      
  firefox:
    image: selenium/node-firefox:4.3.0-20220624
    shm_size: 2gb
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2 #number of browsers
    networks: 
      - network1

  selenium-hub:
    image: selenium/hub:4.3.0-20220624
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks: 
      - network1


  test_bi_lite:
    image: test_bi_lite
    container_name: testbilite
    build:
      context: .
      dockerfile: TestBILite/Dockerfile
    depends_on: 
      - selenium-hub
    networks: 
      - network1
      
networks: 
   network1: