version: '3.4'
services:
  chrome:
    image: selenium/node-chrome:4.3.0-20220624
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks: 
      - ea_network

  edge:
    image: selenium/node-edge:4.3.0-20220624
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks: 
      - ea_network

  firefox:
    image: selenium/node-firefox:4.3.0-20220624
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks: 
      - ea_network

  selenium-hub:
    image: selenium/hub:4.3.0-20220624
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks: 
      - ea_network


  test_bi_lite:
    image: test_bi_lite
    container_name: testbilite
    build:
      context: .
      dockerfile: TestBILite/Dockerfile
    depends_on: 
      - selenium-hub
    networks: 
      - ea_network
      
networks: 
   ea_network: