name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Spawn docker compose to build
      run: docker-compose -f "docker-composer.yml" up -d -build
    - name: Run Tests
      run: |
        echo --Running Tests cases---
        docker-compose -f "docker-compose.yml" up -p Testing --build --exit-code-from test_bi_lite
    - name: Stop containers
      if: ${{ always ()}}
      run: docker-compose -f "docker-compose.yml" down
